# Generated by Django 4.2.25 on 2026-02-17 12:52

import apps.documents.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                default=1,
                upload_to=apps.documents.services.storage.document_upload_path,
            ),
            preserve_default=False,
        ),
    ]
