# Generated by Django 4.2.25 on 2026-02-17 13:37

import apps.documents.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_document_file_path_document_file"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="unique_document_per_org",
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Mark as inactive to hide from normal operations",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.documents.services.storage.document_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_hash__gt", "")),
                fields=("organization", "file_hash"),
                name="unique_document_per_org",
            ),
        ),
    ]
