# Generated by Django 4.2.25 on 2026-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="text_content",
            field=models.TextField(
                blank=True, default="", help_text="Extracted text from the PDF file"
            ),
        ),
    ]
