# Generated by Django 4.2.25 on 2026-02-17 15:30

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_created_at_user_updated_at_and_more"),
        ("documents", "0005_document_text_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="text_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extracted text from the PDF file (populated by async task)",
            ),
        ),
        migrations.DeleteModel(
            name="DocumentEmbedding",
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_chunks",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="idx_chunk_doc_index"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["organization"], name="idx_chunk_org"),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"), name="unique_chunk_per_doc"
            ),
        ),
    ]
