# Generated by Django 4.2.25 on 2026-02-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documentchunk_alter_document_text_content_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="unique_document_per_org",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="idx_doc_file_hash",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_hash",
        ),
    ]
