# Generated by Django 4.2.25 on 2026-02-17 18:51

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_document_unique_document_per_org_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
