# Generated by Django 4.2.25 on 2026-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Chunk metadata: char positions, word count, section info, etc.",
            ),
        ),
    ]
