# Generated by Django 4.2.25 on 2026-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentchunk_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('hr', 'HR'), ('finance', 'Finance'), ('policy', 'Policy'), ('cv', 'CV / Resume'), ('legal', 'Legal'), ('technical', 'Technical'), ('other', 'Other')], db_index=True, default='general', help_text='Document category for filtering and context', max_length=20),
        ),
    ]
